language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: L6xI8/Mm70U2uau6dER2HBBg2g768UKtXYkdipoJHVB2C0VxXc6eTXThxDXhWIvKOZeKcuGFe/XaWkdkiKUPpelaJzH1v6BqVR/sbgn8z8vrCO+RURCZcQWltdx0RMl0qnDuYWxuLi4FHKstTYJS44d8qu+Zo1eg0Gnkhc9gvyiHvcjBJB0uSkyXgrJ0ALE1MBiixtUU8TzM6ssEC7Mfe5VxoXl3RHguaI2VtcGJCFQ8QcC8ByZ0G6h2ey6PZJDn9tHWdIy3GDfR6D7TJMOFM5MMlfKzng1PPBxsG8mJHZ25Bmcsf17Tt8m/N0Xs0skJRcmsGZi0dNypMkw/jEwbWBnqVep6cp5b4oFelCyeUY+BRPhHEObqDmqcxiJ0OYjN7hBOQBRznIg9eUWG3HMzWyotmGVog1QjTz3ZGrDShwSeQfHV+EXEg5JQE5ACeUYO2pmGn7C93XL8qq2IqU0eEclc3yNB3mYZXUJLsV0noGULiAyKrY7gfCn70mEriyheaG2rPzIvH6ESx6c9uFXW9TDeGKzggRKQcEkzNpOZGizuu3t+CxJJULMobc8wBRUOCUsKnWMMfpKArytOPjL5ryXFhWrTm2U2ZPA7gQC/kfXAUNBgo/a2b15H4XfQBAnCM4CxB64zRGnTlV6nyQp3wVxAWqI+aPPquFzJj36+Q2A=
  app: serene-anchorage-61195
  on:
    repo: Taradacktl/animal-tracker
