language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: YzHoHNvBsNZuc+bMVEn0CbbX5xgbUBMKqgKHdsr6Zyq8JLtu0KL5Tme8+wJLO1Bwxese5o1KWOCg/S4y0LDOQa22QJQd2GDcO1HT1tdPumFKOPVPiSRV9Mh44UksODRTy5mXnznich/jpWyfC0quMmx/IYNZ7hhxJwYUZ/YNVe6PV/PGKII5QxlSmqW+QnQq2p+KaWM5Ei14IoIBsH3OGu34eRgoOaYeQtG+isxvImDETE4xC3iOntcjNf4iQz5QMOY7+Uuu74+pGb5ckgZzFkDgurcPgrKWozdOnPtIfdV4Q0PuAfyHYAO3wv7EuplcUkt772zqF4zX4QG15sDhaDNuO4dN4DTaGu3ZGF4QvQcI+rqaeA+Wi8QDvV9MWGSBspKFh0AyRV05rQwpJS0qrlp54jxWKrWC6BtHGaNLrOI/Thnu0ufrwOcQht+3V9NzlVuiwf0JFDHTiA928Qz7x5F/0Y85o0AoWvVkg5kj596bVXrlkDn2xkL+SAAWJghnhTDGLFg2pTx87kmLD4859E1tTS0e38+729uXHY8I/cmF4f+T//fgAT+qU19R4k2XW8zjZ4YMCQHYBjELsNSUjtpCEPRBFLxRbnn8l3Scl6yss5AX1E8DITJmSuAGXG/qzd7lnNKto5w0w8Lj7+vnc9fBYLmwZL9jhwitve7ghuI=
  app: animaltrack
